# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  web:
    build: .
    depends_on:
      - db
      - redis
    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80 --forwarded-allow-ips='*' --proxy-headers"
    volumes:
      - .:/app
    ports:
      - 8008:80
    env_file:
      - .env

volumes:
  postgres_data:
