@startuml ER diagram

entity "User" as user {
  + UserID : uuid
  --
  Name : varchar
  Email : varchar
}

entity "Consent" as consent {
  + ConsentID : uuid
  --
  ConsentType : varchar
  ConsentStatus : varchar
  UserID : int
}

entity "ConsentHistory" as history {
  + HistoryID : uuid
  --
  ConsentID : int
  ChangeDate : datetime
  OldStatus : varchar
  NewStatus : varchar
}

entity "ChangeTracker" as tracker {
  + ChangeID : uuid
  --
  HistoryID : int
  ChangeDate : datetime
  ChangeType : varchar
}

user ||..o{ consent : Gives
consent ||..o{ history : Has
history ||..o{ tracker : Tracks

@enduml