@startuml ER diagram

entity "Consent" as consent {
  + uuid : uuid
  --
  Active : boolean
  Revokable : boolean
  TypeId : uuid
  FlowId : uuid
  ConsentStatus : uuid
  Content : text
}

entity "Type" as type {
  + id : uuid
  --
  Title : varchar
}

entity "Flow" as flow {
  + id : uuid
  --
  Title : varchar
}

entity "History" as history {
  + HistoryID : uuid
  --
  ConsentID : int
  ChangeDate : datetime
  OldStatus : varchar
  NewStatus : varchar
}

entity "ChangeTracker" as tracker {
  + ChangeID : uuid
  --
  HistoryID : int
  ChangeDate : datetime
  ChangeType : varchar
}

entity "SignedConsents" as signed {
  + uuid : uuid // user id from the external system
  --
  ConsentID : uuid
  SignDate : datetime
  SignType : varchar [sign/revoke]
}

signed::ConsentID ||..o{ consent::uuid : n:n
consent ||..o{ history : Has
consent ||..o{ type : Has
consent::FlowId ||..o{ flow::uuid : Has

history ||..o{ tracker : Tracks

@enduml