@startuml
actor User as user

participant "API Gateway" as api
participant "ConsentManager" as cm

alt
user -> api: 
api -> cm: 
cm -> api: 
api -> user: 

user -> api: Give Consent
api -> cm: Manage Consent
cm -> api: Consent Stored
api -> user: Consent Stored

@enduml