@startuml sequence
actor User as user

participant "API Gateway" as api
participant "ConsentManager" as cm

group User opens an app first time
user -> api: Get list of newest Consent
api -> cm: /consent/get_latest
cm -> api: List of consents
api -> user: List of consents
end

group User already has an account
user -> api: Are there any updated policies
api -> cm: /consent/check/{user_uuid}/
cm -> api: List of consents
api -> user: List of consents
else No consents
cm -> api: Empty list
api -> user: Empty list 
end

group Signing Consent
user -> api: Give Consent
api -> cm: /consent/{consent_id}/sign
cm -> api: Consent Stored
api -> user: Confirmed
end

@enduml