@startuml usecase
left to right direction
skinparam packageStyle rect

actor "New user" as new_user
actor "Registered user" as registered_user

package Company {
    actor Admin as admin
    actor Compliance as c
}

rectangle "ConsentManager" {
  rectangle "1. Onboarding flow" {
    usecase "Get terms" as terms
    usecase "Sign consent" as sign
  }

  rectangle "2. Registered user actions" {
    usecase signed as "2.1 View signed consents"
    usecase revoke as "2.2 Revoke consents"
    note right of (revoke)
      - Right to be Forgotten
      - To unsubscribe from 
      the marketing communications
    end note
    usecase history as "View consents change history"
  }

  rectangle "3. Managing" {
    usecase "3.1 Policy management" as manage
    usecase "3.2 Consent Tracking" as tracking    
  }
  
}

new_user --> terms
new_user --> sign

registered_user --> signed
registered_user --> revoke
registered_user --> history

admin --> manage
c --> tracking
@enduml