@startuml
left to right direction
skinparam packageStyle rect

actor Customer as user

package Company {
    actor Compliance as c
    actor Manager as admin
}

rectangle "ConsentManager" {
  usecase "Onboarding" as onboarding
  usecase "Policy Update" as update
  usecase "Compliance" as comliance
  usecase "Consent Tracking" as tracking
  usecase "Avoidance of Regulatory Fines" as avoidance
}

user --> onboarding
admin --> update
c --> tracking
@enduml