@startuml usecase
left to right direction
skinparam packageStyle rect

actor "User" as new_user
actor "Registered user" as registered_user

package Company {
    actor Compliance as c
    actor Admin as admin
}

rectangle "ConsentManager" {
  rectangle "Onboarding flow" {
    usecase "Get terms" as terms
    usecase "Sign consent" as sign
  }

  rectangle "Registered user actions" {
    usecase "View signed consents" as signed
    usecase "Revoke consents" as revoke
    usecase "View change history" as history
  }

  rectangle "Managing" {
    usecase "Policy management" as manage
    usecase "Consent Tracking" as tracking    
  }
  
}

new_user --> terms
new_user --> sign

registered_user --> signed
registered_user --> revoke
registered_user --> history

admin --> manage
c --> tracking
@enduml